package com.doit;

import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
/*
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"
Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lower-case English letters.
 */
public class FindTheDifferenceChar {

	public static void main(String[] args) {

		String s = "abcda";
		String t = "bakcda";

		Map<String, Integer> map1 = new HashMap<>();
		Map<String, Integer> map2 = new HashMap<>();

		String[] sa = s.split("");
		String[] ta = t.split("");

		for (int i = 0; i < t.length(); i++) {
			map2.put(ta[i], map2.get(ta[i]) == null ? 1 : map2.get(ta[i]) + 1);
			if (i < t.length() - 1) {
				map1.put(sa[i], map1.get(sa[i]) == null ? 1 : map1.get(sa[i]) + 1);
			}
		}

		for (Entry<String, Integer> entry : map2.entrySet()) {
			if (!map1.containsKey(entry.getKey()) || entry.getValue() - map1.get(entry.getKey()) != 0) {
				System.out.println(entry.getKey());
				break;
			}
		}
	}

}
